/*
 * File: app/view/Globals.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VACR.view.Globals', {
    extend: 'Ext.Base',

    singleton: true,

    currentRecord: -1,

    doUpdate: function(appBase) {
        var quizData = Ext.data.StoreManager.lookup('quizDataStore');
        var record = quizData.getAt(VACR.view.Globals.currentRecord);
        var pictureQuizView = appBase.down('#pictureQuizView');
        // get the pictures field out of this record
        var picData = record.get('pictures');
        pictureQuizView.store.loadData(picData);

        // First, clear the combobox
        var cmbChoice = appBase.down('#cmbChoice');
        cmbChoice.clearValue();

        // Load the choiceStore with data to updatet the combobox
        var choiceStore = Ext.data.StoreManager.lookup('choiceStore');
        var choiceData = record.get('choices');
        choiceData.sort(function(a,b){return b.choice-a.choice});
        choiceStore.loadData(choiceData);
        // If previously selected a value, set that value in the cbbox
        if(record.selectedchoice > 0)
        {
            cmbChoice.setValue(record.selectedchoice);
        }
    },

    getRandomRow: function(except, theData) {
        var rand = except;
        while(rand == except){
            rand = Ext.Number.randomInt(0, theData.count()-1);
        }
        return theData.getAt(rand).data;
    }

});