/*
 * File: app/view/VACR.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VACR.view.VACR', {
    extend: 'Ext.panel.Panel',

    width: 750,
    layout: {
        type: 'accordion'
    },
    title: 'Visual Aircraft Recognition',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    itemId: 'reviewPanel',
                    collapsed: false,
                    title: 'Review',
                    items: [
                        {
                            xtype: 'form',
                            height: 500,
                            itemId: 'mainPanel',
                            layout: {
                                type: 'border'
                            },
                            collapsed: false,
                            title: '',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    region: 'west',
                                    itemId: 'vacrGrid',
                                    store: 'VacrStore',
                                    viewConfig: {

                                    },
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'name',
                                            text: 'Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'modelno',
                                            text: 'Modelno'
                                        }
                                    ],
                                    listeners: {
                                        select: {
                                            fn: me.onGridpanelSelect,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'panel',
                                    region: 'center',
                                    itemId: 'bottomPanel',
                                    layout: {
                                        type: 'vbox'
                                    },
                                    title: 'Aircraft Detail',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            id: 'detailPanel',
                                            itemId: 'detailPanel',
                                            tpl: [
                                                '',
                                                '<b>Name: {name}</b><br>',
                                                '<b><i>Model: {modelno}</i></b><br>',
                                                ''
                                            ],
                                            layout: {
                                                type: 'fit'
                                            }
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'panel',
                                                    border: 1,
                                                    frame: true,
                                                    height: 450,
                                                    width: 230,
                                                    autoScroll: true,
                                                    items: [
                                                        {
                                                            xtype: 'dataview',
                                                            itemId: 'pictureView',
                                                            autoScroll: true,
                                                            itemSelector: 'div.thumb-wrap',
                                                            itemTpl: [
                                                                '<div style="margin-bottom: 10px;" class="thumb-wrap">',
                                                                '    <img src="images/{picture}" width="200" />',
                                                                '        </div>'
                                                            ],
                                                            store: 'pictureStore'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    itemId: 'descriptionPanel',
                                                    width: 300,
                                                    title: 'Characteristics',
                                                    items: [
                                                        {
                                                            xtype: 'dataview',
                                                            itemId: 'descriptionView',
                                                            tpl: [
                                                                '<ul>',
                                                                '</ul>'
                                                            ],
                                                            itemSelector: 'div.thumb-wrap',
                                                            itemTpl: [
                                                                '<div style="margin-bottom: 10px;" class="thumb-wrap">',
                                                                '    <li>{description}</li>',
                                                                '</div>'
                                                            ],
                                                            store: 'descriptionStore'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    itemId: 'practicePanel',
                    collapsed: false,
                    title: 'Practice Test',
                    items: [
                        {
                            xtype: 'form',
                            height: 500,
                            autoScroll: true,
                            bodyPadding: 10,
                            title: '',
                            items: [
                                {
                                    xtype: 'dataview',
                                    itemId: 'pictureQuizView',
                                    autoScroll: true,
                                    itemSelector: 'div.thumb-wrap',
                                    itemTpl: [
                                        '<div style="margin-bottom: 10px;" class="thumb-wrap">',
                                        '    <img src="images/{picture}" width="200" />',
                                        '        </div>'
                                    ],
                                    store: 'quizPictureStore'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    autoRender: true,
                                    itemId: 'cmbChoice',
                                    maxWidth: 300,
                                    fieldLabel: 'Select correct choice',
                                    labelWidth: 150,
                                    autoSelect: false,
                                    displayField: 'description',
                                    queryMode: 'local',
                                    store: 'choiceStore',
                                    valueField: 'choice'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnNext',
                                    text: 'Next',
                                    listeners: {
                                        click: {
                                            fn: me.onBtnNextClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnPrev',
                                    text: 'Next',
                                    listeners: {
                                        click: {
                                            fn: me.onBtnPrevClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ],
                    listeners: {
                        expand: {
                            fn: me.onPracticePanelExpand,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onGridpanelSelect: function(selModel, record, index, options) {
        // grab a reference to the detailPanel via itemId
        // the # in front of the id indicates that we would like to grab a reference by
        var detailPanel = this.down('#detailPanel');
        // update the detailPanel with data
        // this will trigger the tpl to become updates
        detailPanel.update(record.data);
        // grab a reference to the pictureView, notice we use down here instead of child
        // because down will go down the container hierarchy at any depth and child will
        // only retrieve direct children
        var picView = this.down('#pictureView');
        // get the pictures field out of this record
        var picData = record.get('pictures');
        picView.store.loadData(picData);
        // get the descriptions field
        var descData = record.get('descriptions');
        var descView = this.down('#descriptionView');
        descView.store.loadData(descData);
    },

    onBtnNextClick: function(button, e, options) {
        var quizData = Ext.data.StoreManager.lookup('quizDataStore');
        //Check if at end
        if(VACR.view.Globals.currentRecord >= quizData.getCount() - 1)
        {
            //Reset current record
            VACR.view.Globals.currentRecord = 0;    
        }
        else
        {
            //Increase current record
            ++VACR.view.Globals.currentRecord;
        }

        VACR.view.Globals.doUpdate(this);

    },

    onBtnPrevClick: function(button, e, options) {
        var quizData = Ext.data.StoreManager.lookup('quizDataStore');
        //Check if at end
        if(VACR.view.Globals.currentRecord === 0)
        {
            //Reset current record
            VACR.view.Globals.currentRecord = quizData.getCount() - 1;    
        }
        else
        {
            //Increase current record
            --VACR.view.Globals.currentRecord;
        }

        VACR.view.Globals.doUpdate(this);
    },

    onPracticePanelExpand: function(p, options) {
        // Build data collection
        var theData = this.down('#vacrGrid').store;
        var quizData = Ext.data.StoreManager.lookup('quizDataStore');
        theData.each(function(item, index, count) { 
            var recID = item.data.id;
            var recDesc = item.data.modelno + " - " + item.data.name;
            quizData.add({id: recID, selectedchoice: -1, choices: 
                [{choice:0, description: recDesc},
                {choice:2, description: "C130"},
                {choice:1, description: "C131"},
                {choice:3, description: "C132"}],
                pictures: item.data.pictures
            });
        });
        VACR.view.Globals.currentRecord = 0;
        var record = quizData.getAt(VACR.view.Globals.currentRecord);
        var pictureQuizView = this.down('#pictureQuizView');
        // get the pictures field out of this record
        var picData = record.get('pictures');
        pictureQuizView.store.loadData(picData);

        // Load the choiceStore with data
        var choiceStore = Ext.data.StoreManager.lookup('choiceStore');
        var choiceData = record.get('choices');
        choiceStore.loadData(choiceData);

    }

});