/*
 * File: app/controller/SessionManager.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VACR.controller.SessionManager', {
    extend: 'Ext.Base',

    singleton: true,

    BTN_OK: 'ok',
    BTN_YES: 'yes',
    SESSION_ABOUT_TO_TIMEOUT_PROMT_INTERVAL_IN_MIN: '.25',
    GRACE_PERIOD_BEFORE_EXPIRING_SESSION_IN_MIN: '1',
    SESSION_KILL_URL: 'auth/process.php',

    toMilliseconds: function(minutes) {
        return minutes * 60 * 1000;
    },

    simulateAjaxRequest: function() {
        Ext.Ajax.request({
            url: SESSION_KILL_URL,
            success: Ext.emptyFn,
            failure: Ext.emptyFn
        });
    },

    simulateAjaxRequestToKillServerSession: function() {
        Ext.Ajax.request({
            url: App.SESSION_KILL_URL,
            success: Ext.emptyFn,
            failure: Ext.emptyFn
        });
    }

});